-- MySQL Script generated by MySQL Workbench
-- 03/07/17 15:08:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema web_service_phonebook
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema web_service_phonebook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `web_service_phonebook` DEFAULT CHARACTER SET utf8 ;
USE `web_service_phonebook` ;

-- -----------------------------------------------------
-- Table `web_service_phonebook`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_service_phonebook`.`clients` (
  `client_login` VARCHAR(20) NOT NULL,
  `client_pass` VARCHAR(20) NOT NULL,
  `client_full_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`client_login`),
  UNIQUE INDEX `client_login_UNIQUE` (`client_login` ASC),
  UNIQUE INDEX `client_full_name_UNIQUE` (`client_full_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web_service_phonebook`.`phonebook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_service_phonebook`.`phonebook` (
  `client_login` VARCHAR(20) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `second_name` VARCHAR(45) NOT NULL,
  `additional_name` VARCHAR(45) NOT NULL,
  `mobile_number` VARCHAR(45) NOT NULL,
  `home_number` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`client_login`),
  CONSTRAINT `fk_phonebook_clients`
    FOREIGN KEY (`client_login`)
    REFERENCES `web_service_phonebook`.`clients` (`client_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
