-- MySQL Script generated by MySQL Workbench
-- 03/07/17 11:00:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema web_service_phonebook
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema web_service_phonebook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `web_service_phonebook` DEFAULT CHARACTER SET utf8 ;
USE `web_service_phonebook` ;

-- -----------------------------------------------------
-- Table `web_service_phonebook`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_service_phonebook`.`clients` (
  `client_login` VARCHAR(20) NOT NULL,
  `client_pass` VARCHAR(20) NOT NULL,
  `client_full_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`client_login`),
  UNIQUE INDEX `client_login_UNIQUE` (`client_login` ASC),
  UNIQUE INDEX `client_full_name_UNIQUE` (`client_full_name` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
